name: Daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

concurrency:
  group: daily
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: E2E tests (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Install JBrowse CLI
        run: npm install -g @jbrowse/cli
      - name: Setup JBrowse nightly
        run: jbrowse create .test-jbrowse-nightly --nightly
      - name: Run E2E tests
        run: TEST_JBROWSE_VERSION=nightly yarn vitest run test/
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-nightly
          path: test-screenshots/
