name: Daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E tests (${{ matrix.jbrowse-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jbrowse-version: [nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Install JBrowse CLI
        run: npm install -g @jbrowse/cli
      - name: Setup JBrowse ${{ matrix.jbrowse-version }}
        run: jbrowse create .test-jbrowse-nightly --nightly
      - name: Run E2E tests
        run: TEST_JBROWSE_VERSION=${{ matrix.jbrowse-version }} yarn vitest run test/
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.jbrowse-version }}
          path: test-screenshots/
